name: "danger"

on:
  pull_request:
    branches:
      - "main"
    types: [ "opened", "synchronize", "closed" ]

jobs:
  danger:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v4"
      - name: "setup ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          bundler-cache: true
      - uses: MeilCli/danger-action@v6
        with:
          danger_file: "Dangerfile"
          danger_id: "danger-pr"
          install_path: "vendor/bundle"
          plugins_file: "Gemfile"
        env:
          DANGER_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
