name: "danger"

on:
  pull_request:
    branches:
      - "main"
    types: [ "opened", "synchronize", "closed" ]

jobs:
  danger:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v4"
      - name: "setup ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          bundler-cache: true
