# @EnKUMAによる以下の記事を参考に作成
# 
# GitHubActionsのCI/CDにyamllintを組み込んで作業の安全性を高める
# https://qiita.com/EnKUMA/items/6974e310221fc9765c2f
name: yamllint

on:
  pull_request:
    branches:
      - "main"
    types: [opened, synchronize, closed]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Create PR comment of reviewdog"
        uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-pr-review
          level: warning
          yamllint_flags: '-c .yamllint ./.github/workflows/'
      - name: "lint All The Things in Repository"
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_file_or_dir: ./.github/workflows/
          yamllint_config_filepath: .yamllint
